# DC schema

CREATE TABLE DEVICE (
  ID         BIGINT       NOT NULL AUTO_INCREMENT,
  DEVICE_UID VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UC_DEVICE_DEVICE_UID (DEVICE_UID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE USER (
  ID             BIGINT      NOT NULL AUTO_INCREMENT,
  DEVICE_ID      BIGINT      NOT NULL,
  NAME           VARCHAR(50) NOT NULL,
  STATUS         CHAR(1)     NULL     DEFAULT 'A',
  CONNECTED_AT   TIMESTAMP   NULL     DEFAULT NULL,
  EXITED_AT      TIMESTAMP   NULL     DEFAULT NULL,
  LAST_PLAYED_AT TIMESTAMP   NULL     DEFAULT NULL,
  DELETED_AT     TIMESTAMP   NULL     DEFAULT NULL,
  UPDATED_AT     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATED_AT     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_DEVICE_ID FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE LINKED_ACCOUNT (
  ID               BIGINT(20)   NOT NULL AUTO_INCREMENT,
  USER_ID          BIGINT(20)   NOT NULL,
  PROVIDER_KEY     VARCHAR(255) NOT NULL,
  PROVIDER_USER_ID VARCHAR(255) NOT NULL,
  CREATED_AT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FK_LINKED_ACCOUNT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE TOKEN (
  ID         BIGINT      NOT NULL AUTO_INCREMENT,
  USER_ID    BIGINT(20)  NOT NULL,
  TOKEN      VARCHAR(64) NOT NULL,
  TYP        CHAR(1)     NOT NULL,
  EXPIRED_AT TIMESTAMP   NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UC_TOKEN_TOKEN (TOKEN),
  CONSTRAINT FK_TOKEN_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE USER_SCORE (
  ID         BIGINT     NOT NULL AUTO_INCREMENT,
  USER_ID    BIGINT(20) NOT NULL,
  SCORE      BIGINT(20) NOT NULL,
  STEP       BIGINT(20) NOT NULL,
  UPDATED_AT TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UC_USER_SCORE_USER_ID (USER_ID),
  CONSTRAINT FK_USER_SCORE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE GAME (
  ID         BIGINT     NOT NULL AUTO_INCREMENT,
  USER_ID    BIGINT(20) NOT NULL,
  SCORE      BIGINT(20) NULL,
  STEP       BIGINT(20) NULL,
  STARTED_AT TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ENDED_AT   TIMESTAMP  NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_GAME_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE FRIEND (
  ID         BIGINT     NOT NULL AUTO_INCREMENT,
  USER_ID    BIGINT(20) NOT NULL,
  FRIEND_ID  BIGINT(20) NOT NULL,
  CREATED_AT TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT UC_USER_SCORE_USER_ID UNIQUE (USER_ID, FRIEND_ID),
  CONSTRAINT FK_FRIEND_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_FRIEND_FRIEND_ID FOREIGN KEY (FRIEND_ID) REFERENCES USER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;